// <auto-generated />
using System;
using G_NET_12_EF02.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G_NET_12_EF03.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430164219_EventHub")]
    partial class EventHub
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G_NET_12_EF02.Model.Attendee", b =>
                {
                    b.Property<int>("AttendeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("AttendeeID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Badge", b =>
                {
                    b.Property<int>("BadgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeID"));

                    b.Property<int>("AttendeeID")
                        .HasColumnType("int");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("BadgeID");

                    b.HasIndex("AttendeeID")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"), 10L, 10);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentEventID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("ParentEventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Organizer", b =>
                {
                    b.Property<int>("OrganizerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerID"));

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrganizerID");

                    b.ToTable("organizers");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Profile", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileID");

                    b.HasIndex("OrganizerID")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Registration", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("AttendeeID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("EventID", "AttendeeID");

                    b.HasIndex("AttendeeID");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Attendee", b =>
                {
                    b.OwnsOne("G_NET_12_EF02.Model.Address", "Address", b1 =>
                        {
                            b1.Property<int>("AttendeeID")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AttendeeID");

                            b1.ToTable("Attendees");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeID");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Badge", b =>
                {
                    b.HasOne("G_NET_12_EF02.Model.Attendee", "BagdeAtt")
                        .WithOne("AttendeeBadge")
                        .HasForeignKey("G_NET_12_EF02.Model.Badge", "AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BagdeAtt");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Event", b =>
                {
                    b.HasOne("G_NET_12_EF02.Model.Organizer", "EVOrganizer")
                        .WithMany("OrgEvent")
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_NET_12_EF02.Model.Event", "ParentEvent")
                        .WithMany("Sessions")
                        .HasForeignKey("ParentEventID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EVOrganizer");

                    b.Navigation("ParentEvent");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Profile", b =>
                {
                    b.HasOne("G_NET_12_EF02.Model.Organizer", "OrganizerProf")
                        .WithOne("ProfileOrg")
                        .HasForeignKey("G_NET_12_EF02.Model.Profile", "OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizerProf");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Registration", b =>
                {
                    b.HasOne("G_NET_12_EF02.Model.Attendee", "ReAttendee")
                        .WithMany("ATTRegistration")
                        .HasForeignKey("AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G_NET_12_EF02.Model.Event", "ReEvent")
                        .WithMany("EVRegistration")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReAttendee");

                    b.Navigation("ReEvent");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Attendee", b =>
                {
                    b.Navigation("ATTRegistration");

                    b.Navigation("AttendeeBadge");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Event", b =>
                {
                    b.Navigation("EVRegistration");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("G_NET_12_EF02.Model.Organizer", b =>
                {
                    b.Navigation("OrgEvent");

                    b.Navigation("ProfileOrg");
                });
#pragma warning restore 612, 618
        }
    }
}
